// Generated by https://quicktype.io

export interface ProductDetails {
  sold_quantity: number;
  description: string;
  price: number;
  title: string;
  picture: string;
  condition: string;
}

export interface ProductDetailProps {
  productDetail: ProductDetails;
  error: string;
}
